# Generated by Django 4.2.7 on 2024-01-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recepy_name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='recipename')),
            ],
        ),
    ]
