# Generated by Django 4.2.7 on 2023-12-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
