# Generated by Django 4.2.7 on 2023-12-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services2', '0002_student_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
    ]
